services:
  ocr-service:
    build: .
    container_name: ocr-service
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_LOCATION=${GCP_LOCATION}
      - GCP_PROCESSOR_ID=${GCP_PROCESSOR_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./secrets:/secrets:ro
